---
- name: Configurações de Armazenamento (LVM) e Servidor NFS no arq
  hosts: arq
  become: yes
  vars_files:
    - vars.yml # Garante que as variáveis de nome/matrícula estejam disponíveis

  tasks:
    - name: Instalar pacote LVM2
      ansible.builtin.apt:
        name: lvm2
        state: present
      tags:
        - arq
        - lvm

    # --- Configurações LVM ---
    - name: Utilizar os 3 discos para criar um Volume Group (VG) chamado dados
      community.general.lvg:
        vg: dados
        pvs: /dev/sdb,/dev/sdc,/dev/sdd # ATENÇÃO: CONFIRME OS NOMES DOS DISCOS NA VM 'arq'
        state: present
      tags:
        - arq
        - lvm

    - name: Criar um Logical Volume (LV) chamado ifpb com 15 GB de tamanho
      community.general.lvol:
        vg: dados
        lv: ifpb
        size: 15G
        state: present
      tags:
        - arq
        - lvm

    - name: Formatar o LV ifpb com o sistema de arquivos ext4
      community.general.filesystem:
        fstype: ext4
        dev: /dev/mapper/dados-ifpb
      tags:
        - arq
        - lvm

    - name: Criar diretório /dados
      ansible.builtin.file:
        path: /dados
        state: directory
        mode: '0755'
      tags:
        - arq
        - lvm

    - name: Configurar a partição ifpb para ser montada automaticamente no diretório /dados
      ansible.builtin.mount:
        path: /dados
        src: /dev/mapper/dados-ifpb
        fstype: ext4
        opts: defaults
        state: mounted
      tags:
        - arq
        - lvm

    # --- Configurações NFS Server ---
    - name: Instalar servidor NFS
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
      tags:
        - arq
        - nfs

    - name: Criar o usuário nfs-ifpb
      ansible.builtin.user:
        name: nfs-ifpb
        state: present
        shell: /sbin/nologin # Remover o shell do usuário nfs-ifpb para aumentar a segurança
      tags:
        - arq
        - nfs

    # Novas tarefas para obter UID e GID do nfs-ifpb de forma robusta
    - name: Obter UID do usuário nfs-ifpb
      ansible.builtin.command: id -u nfs-ifpb
      register: nfs_ifpb_uid_result
      changed_when: false # Esta tarefa não altera o sistema
      tags:
        - arq
        - nfs

    - name: Obter GID do usuário nfs-ifpb
      ansible.builtin.command: id -g nfs-ifpb
      register: nfs_ifpb_gid_result
      changed_when: false # Esta tarefa não altera o sistema
      tags:
        - arq
        - nfs

    - name: Criar diretório /dados/nfs
      ansible.builtin.file:
        path: /dados/nfs
        state: directory
        # Definindo proprietário e grupo do diretório NFS para nfs-ifpb
        owner: nfs-ifpb
        group: nfs-ifpb
        mode: '0770' # rw para owner/group, sem perm para outros
      tags:
        - arq
        - nfs

    - name: Configurar o servidor NFS para compartilhar o diretório /dados/nfs com qualquer host da rede 192.168.56.0/24
      ansible.builtin.lineinfile:
        path: /etc/exports
        # Usar as variáveis registradas dos comandos id -u e id -g
        line: "/dados/nfs 192.168.56.0/24(rw,sync,no_subtree_check,all_squash,anonuid={{ nfs_ifpb_uid_result.stdout }},anongid={{ nfs_ifpb_gid_result.stdout }})"
        state: present
      notify: Exportfs -r
      tags:
        - arq
        - nfs

  handlers:
    - name: Exportfs -r
      ansible.builtin.command: exportfs -r
